CREATE TABLE IF NOT EXISTS patios(
ID             INTEGER PRIMARY KEY NOT NULL,
NAME           TEXT    NOT NULL,
CAPACITY       INT     NOT NULL,
ADDRESS        CHAR(50),
PROPRIETARY    CHAR(50),
CONTACT        CHAR(12),
DAILY_FEE      REAL);
CREATE TABLE IF NOT EXISTS carros(
 ID             INTEGER PRIMARY KEY NOT NULL,
 ID_PATIO       INTEGER NOT NULL,
 FOREIGN KEY(ID_PATIO) REFERENCES patios(ID));