#include "Carro.h"

namespace model {


    Carro::Carro() {

    }

    Carro::Carro(int pHora, int horas) {
        _pHora = pHora;
        _horas = horas;
    }

    int Carro::calculaPreco() const {
        return _horas*_pHora;
    }

    //autogenerated getters and setters
    int Carro::getPHora() const {
        return _pHora;
    }

    void Carro::setPHora(int pHora) {
        _pHora = pHora;
    }

    int Carro::getHoras() const {
        return _horas;
    }

    void Carro::setHoras(int horas) {
        _horas = horas;
    }


    //end of autogenerated getters and setters

} // model