#ifndef INC_20232_TEAM_14_MOTO_H
#define INC_20232_TEAM_14_MOTO_H

#include "Veiculo.h"
#include <vector>
#include <string>

namespace model {

    class Moto : public Veiculo {

    private:

        std::string _id;
        bool _capacete;
        bool _carenagem;
        bool _bau;
        bool _ferramentas;
        int _suspDianteira;
        int _suspTraseira;
        int _guidao;
        int _sistEletrico;
        int _escapamento;

    public:

        //constructor
        Moto(const std::string &os, const std::string &solicitacao, const std::string &funcionario,
             const std::string &placaReboque, const std::string &motivo, int estadoVeiculo, bool blitz,
             const std::string &local, const std::string &placa, const std::string &marca, const std::string &modelo,
             int ano, const std::string &cidade, const std::string &chassi, int km, int hodometro,
             const std::string &ocorrencia, const std::string &policial, const std::string &data,
             const std::string &horario, const std::string &objetos, const std::string &observacoes, int rodas,
             int retrovisores, const std::string &id, bool capacete, bool carenagem, bool bau, bool ferramentas,
             int suspDianteira, int suspTraseira, int guidao, int sistEletrico, int escapamento);

        //autogenerated getters and setters
        const std::string &get_id() const;
        void set_id(const std::string &id);
        bool get_capacete() const;
        void set_capacete(bool capacete);
        bool get_carenagem() const;
        void set_carenagem(bool carenagem);
        bool get_bau() const;
        void set_bau(bool bau);
        bool get_ferramentas() const;
        void set_ferramentas(bool ferramentas);
        int get_suspDianteira() const;
        void set_suspDianteira(int suspDianteira);
        int get_suspTraseira() const;
        void set_suspTraseira(int suspTraseira);
        int get_guidao() const;
        void set_guidao(int guidao);
        int get_sistEletrico() const;
        void set_sistEletrico(int sistEletrico);
        int get_escapamento() const;
        void set_escapamento(int escapamento);
        //end of autogenerated getters and setters

        virtual bool stob(const std::string& str); //string to bool

    };


}

#endif //INC_20232_TEAM_14_MOTO_H
