#ifndef INC_20232_TEAM_14_MOTO_H
#define INC_20232_TEAM_14_MOTO_H

#include "Veiculo.h"
#include <vector>
#include <string>

namespace model {

    class Moto : public Veiculo {

    private:

        std::string _id;
        bool _capacete;
        bool _carenagem;
        bool _bau;
        bool _ferramentas;
        int _suspDianteira;
        int _suspTraseira;
        int _guidao;
        int _sistEletrico;
        int _escapamento;

    public:

        //constructor Moto.h (dados de veículo como parâmetro e um vector contendo os dados de Moto que serão tratados no construtor)
        Moto(std::string os, std::string solicitacao, std::string funcionario, std::string placa_reboque, std::string motivo, int estado_veiculo, bool blitz, std::string local, std::string placa, std::string marca, std::string modelo, int ano, std::string cidade, std::string chassi, int km, int hodometro, std::string ocorrencia, std::string policial, std::string data, std::string horario,std::string objetos, std::string observacoes, int rodas, int retrovisores, std::vector<std::string> &_checklist);

        //autogenerated getters and setters
        const std::string &get_id() const;
        void set_id(const std::string &id);
        bool get_capacete() const;
        void set_capacete(bool capacete);
        bool get_carenagem() const;
        void set_carenagem(bool carenagem);
        bool get_bau() const;
        void set_bau(bool bau);
        bool get_ferramentas() const;
        void set_ferramentas(bool ferramentas);
        int get_suspDianteira() const;
        void set_suspDianteira(int suspDianteira);
        int get_suspTraseira() const;
        void set_suspTraseira(int suspTraseira);
        int get_guidao() const;
        void set_guidao(int guidao);
        int get_sistEletrico() const;
        void set_sistEletrico(int sistEletrico);
        int get_escapamento() const;
        void set_escapamento(int escapamento);
        //end of autogenerated getters and setters

        virtual bool stob(const std::string& str); //string to bool

    };


}

#endif //INC_20232_TEAM_14_MOTO_H
