#ifndef INC_20232_TEAM_14_VEICULO_H
#define INC_20232_TEAM_14_VEICULO_H
#include <string>
#include "Model.h"

namespace model {

    class Veiculo : Model{

    protected:

        std::string _os;                        //Ordem de serviço
        std::string _solicitacao;               //Quem solicitou a apreensão (PM,PRV,etc...)
        std::string _funcionario;               //Funcionário que realizou a apreensão
        std::string _placa_reboque;             //Placa do veículo do pátio (caminhão ou carro) que realizou a apreensão
        std::string _motivo;                    //(Inf. Trânsito/Crime de Trânsito/Falta de Licenciamento/Etc... -> são vários, o usuário que vai escrever)
        int _estado_veiculo;                    //(1)Ruim/(2)Regular/(3)Bom
        bool _blitz;                            //(1)Sim/(2)Não
        std::string _local;                     //Local de apreensão do veículo
        std::string _placa;                     //Placa do veículo
        std::string _marca;                     //Marca do veículo
        std::string _modelo;                    //Modelo do veículo
        int _ano;                               //Ano de fabricação do veículo
        std::string _cidade;                    //Cidade que consta na placa do veículo
        std::string _chassi;                    //Chassi do veículo
        int _km;                                //Distancia do patio ao local de apreensão do veiculo
        int _hodometro;                         //Quantidade de km que o carro ja percorreu
        std::string _ocorrencia;                //Número da ocorrência da apreensão
        std::string _policial;                  //Policial responsável pela apreensão
        std::string _data;                      //Data de Apreensão
        std::string _horario;                   //Horário de Apreensão
        std::string _objetos;                   //Objetos que estavam dentro do veículo
        std::string _observacoes;               //Observações a mais, se for necessário
        int _rodas;                             //(0)Inexistente/(1)Amassado/(2)Riscado/(3)Quebrado/(4)Bom estado
        int _retrovisores;                      //(0)Inexistente/(1)Amassado/(2)Riscado/(3)Quebrado/(4)Bom estado

    public:

        //Construtor Veiculo.h

        Veiculo(const std::string &os, const std::string &solicitacao, const std::string &funcionario,
                const std::string &placaReboque, const std::string &motivo, int estadoVeiculo, bool blitz,
                const std::string &local, const std::string &placa, const std::string &marca, const std::string &modelo,
                int ano, const std::string &cidade, const std::string &chassi, int km, int hodometro,
                const std::string &ocorrencia, const std::string &policial, const std::string &data,
                const std::string &horario, const std::string &objetos, const std::string &observacoes, int rodas,
                int retrovisores);

        //autogenerated getters and setters
        virtual const std::string &get_os() const;
        virtual void set_os(const std::string &_os);
        virtual const std::string &get_solicitacao() const;
        virtual void set_solicitacao(const std::string &_solicitacao);
        virtual const std::string &get_funcionario() const;
        virtual void set_funcionario(const std::string &_funcionario);
        virtual const std::string &get_placa_reboque() const;
        virtual void set_placa_reboque(const std::string &_placa_reboque);
        virtual const std::string &get_motivo() const;
        virtual void set_motivo(const std::string &_motivo);
        virtual const int &get_estado_veiculo() const;
        virtual void set_estado_veiculo(const int &_estado_veiculo);
        virtual const bool &get_blitz() const;
        virtual void set_blitz(const bool &_blitz);
        virtual const std::string &get_local() const;
        virtual void set_local(const std::string &_local);
        virtual const std::string &get_placa() const;
        virtual void set_placa(const std::string &_placa);
        virtual const std::string &get_marca() const;
        virtual void set_marca(const std::string &_marca);
        virtual const std::string &get_modelo() const;
        virtual void set_modelo(const std::string &_modelo);
        virtual const int &get_ano() const;
        virtual void set_ano(const int &_ano);
        virtual const std::string &get_cidade() const;
        virtual void set_cidade(const std::string &_cidade);
        virtual const std::string &get_chassi() const;
        virtual void set_chassi(const std::string &_chassi);
        virtual const int &get_km() const;
        virtual void set_km(const int &_km);
        virtual const int &get_hodometro() const;
        virtual void set_hodometro(const int &_hodometro);
        virtual const std::string &get_ocorrencia() const;
        virtual void set_ocorrencia(const std::string &_ocorrencia);
        virtual const std::string &get_policial() const;
        virtual void set_policial(const std::string &_policial);
        virtual const std::string &get_data() const;
        virtual void set_data(const std::string &_data);
        virtual const std::string &get_horario() const;
        virtual void set_horario(const std::string &_horario);
        virtual const std::string &get_objetos() const;
        virtual void set_objetos(const std::string &_objetos);
        virtual const std::string &get_observacoes() const;
        virtual void set_observacoes(const std::string &_observacoes);
        virtual const int &get_rodas() const;
        virtual void set_rodas(const int &_rodas);
        virtual const int &get_retrovisores() const;
        virtual void set_retrovisores(const int &_retrovisores);
        //end of autogenerated getters and setters

        //Verificador de Ano Bissexto -> Ainda não serve de nada
        virtual bool anoBissexto(int ano);

        //Calcula os dias entre a data de apreensão e liberação de veículo para realizar o orçamento  -> Ainda não serve de nada
        //Ainda não sei se a data virá separada em dia/mes/ano ou virá no formato de uma string, por enquanto imagino que seja recebida separadamente
        //virtual int calcDias(int dia_Liberacao, int mes_Liberacao, int ano_Liberacao);

    };

} // model

#endif //INC_20232_TEAM_14_VEICULO_H