

#include "Veiculo.h"

namespace model {





    //autogenerated getters and setters
    const std::string &Veiculo::getPlaca() const {
        return _placa;
    }

    void Veiculo::setPlaca(const std::string &placa) {
        _placa = placa;
    }

    const std::string &Veiculo::getTipo() const {
        return _tipo;
    }

    void Veiculo::setTipo(const std::string &tipo) {
        _tipo = tipo;
    }
    //autogenerated getters and setters
} // model
